### ISSUE TITLE
error in got/source/create.js -  got.stream = (url, options) => got(url, {...options, stream: true});

### ISSUE THREAD

**Issue by popey** [twobucks/wethr#4]
Seems something broke between 1.5.1 and 1.5.2. I'm using the snap of wethr on Ubuntu. `snap install wethr` gets 1.5.1 and works fine. Using `snap install wethr --edge` on the same system breaks as below.

Does 1.5.2 require a newer node or some other dependency previously not needed?

```
/snap/wethr/50/lib/node_modules/wethr/node_modules/got/source/create.js:49
        got.stream = (url, options) => got(url, {...options, stream: true});
                                                 ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/snap/wethr/50/lib/node_modules/wethr/node_modules/got/source/index.js:3:16)
```

**Comment by dinodsaurus** [comment]
Hey @popey thanks for reporting this, it looks like the spread operator of  `got` is causing some trouble.

**Comment by silvenon** [comment]
@popey which version of Node are you using? Seems like [spreading only works for Node v8.6.0+](https://node.green/#ES2018-features-object-rest-spread-properties).

**Comment by popey** [comment]
@silvenon You're right, I was using an older (default on my system) version. I have bumped it and that's fixed this issue. Thank you!
